version: 3

project:
  locator: SolaceLabs_ep-openapi-node
  id: SolaceLabs_ep-openapi-node
  name: ep-openapi-node
  teams: []
  labels:
    - javascript

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    exclude:
      - "./.git"
      - "./.github"

paths:
  exclude:
    - ./.git
    - ./.github

telemetry:
  scope: full
