/** @category Logging */
export enum EEpSdkLoggerCodes {
  SERVICE_GET = "SERVICE_GET",
  SERVICE_CREATE = "SERVICE_CREATE",

  TASK_EXECUTE_START = "TASK_EXECUTE_START",
  TASK_EXECUTE_DONE = "TASK_EXECUTE_DONE",

  TASK_EXECUTE_PRESENT_START = "TASK_EXECUTE_PRESENT_START",
  TASK_EXECUTE_ABSENT_START = "TASK_EXECUTE_ABSENT_START",
  
  TASK_EXECUTE_START_GET = "TASK_EXECUTE_START_GET",
  TASK_EXECUTE_API_GET = "TASK_EXECUTE_API_GET",
  TASK_EXECUTE_DONE_GET = "TASK_EXECUTE_DONE_GET",

  TASK_EXECUTE_START_CREATE = "TASK_EXECUTE_START_CREATE",
  TASK_EXECUTE_CREATE = "TASK_EXECUTE_CREATE",
  TASK_EXECUTE_DONE_CREATE = "TASK_EXECUTE_DONE_CREATE",

  TASK_EXECUTE_START_IS_UPDATE_REQUIRED = "TASK_EXECUTE_START_IS_UPDATE_REQUIRED",
  TASK_EXECUTE_DONE_IS_UPDATE_REQUIRED = "TASK_EXECUTE_DONE_IS_UPDATE_REQUIRED",
  
  TASK_EXECUTE_START_UPDATE = "TASK_EXECUTE_START_UPDATE",
  TASK_EXECUTE_UPDATE = "TASK_EXECUTE_UPDATE",
  TASK_EXECUTE_DONE_UPDATE = "TASK_EXECUTE_DONE_UPDATE",

  TASK_EXECUTE_START_DELETE = "TASK_EXECUTE_START_DELETE",
  TASK_EXECUTE_DONE_DELETE = "TASK_EXECUTE_DONE_DELETE",

  TASK_EXECUTE_RESULT = "TASK_EXECUTE_RESULT",

}
